### ISSUE TITLE
JUnit tests fail across platforms

### ISSUE THREAD

**Issue by chrdebru** [uvm-plaid/chorus#4]
The string comparisons in the JUnit tests fail on different platforms (a line separator issue). Can be quickly resolved by removing the carriage return in the results.

**Comment by jnear** [comment]
Sorry for the delay in addressing this. The tests pass for me on Linux, and I don't see carriage returns in the results files. What platform are you on, where they fail? Thanks!

**Comment by chrdebru** [comment]
They do not fail on my personal machine (Mac OS X), but they do fail on my organization's machine (Windows 10). It's because the string representations of the generated SQL use \r\n on Windows and the strings in the tests use \n. So the strings are never equal. A dirty solution would be to replace all occurrences of \r with an empty string.

**Comment by jnear** [comment]
I don't have a windows machine to test on, but I have pushed commit 433502fe7025e7d480e24a51bcec200a13f66f8d which hopefully fixes this. If it doesn't, please re-open the issue. Thank you!
